"""congratulation

Revision ID: 69116444f9f4
Revises: db4561a48734
Create Date: 2024-07-06 14:10:23.155246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69116444f9f4'
down_revision: Union[str, None] = 'db4561a48734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congratulations', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('congratulations', 'is_read')
    # ### end Alembic commands ###
